name: Deploy .NET Core 9 API to IIS Server

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Setup .NET 9 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.304'

    - name: Restore dependencies
      run: dotnet restore be-ipubers-kartan/be-ipubers-kartan.csproj

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish --configuration Release --no-build --output ./publish

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: api-publish
        path: ./publish

    - name: Deploy to Remote IIS Server
      uses: RasmusBuchholdt/simply-web-deploy@2.0.0
      with:
        # The name of your website as it appears in IIS Manager
        website-name: ${{ secrets.WEBSITE_NAME }}

        # The IP address or DNS name of your remote IIS server
        server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}

        # The username for an account with deployment permissions on the server
        server-username: ${{ secrets.SERVER_USERNAME }}

        # The password for that user account
        server-password: ${{ secrets.SERVER_PASSWORD }}
        
        # The path to your published application from the previous step
        source-path: './publish'
